
# Board settings.
#BOARD = pro.menu.cpu.8MHzatmega328

LIB_DIRS = ../../ /local/arduino-100/hardware/arduino/avr/libraries/SPI/ /local/arduino-100/hardware/arduino/avr/libraries/Wire/ /local/arduino-100/hardware/arduino/avr/libraries/Wire/utility/

include ../../../Makefile.master

