
# Board settings.
#BOARD = atmega328

LIB_DIRS = ../../ /local/arduino-100/libraries/SPI/ /local/arduino-100/libraries/Wire/ /local/arduino-100/libraries/Wire/utility/

include ../../../Makefile.master

