
# Board settings.
BOARD = pro.menu.cpu.8MHzatmega328

LIB_DIRS = ../../ /local/arduino/hardware/arduino/avr/libraries/SPI/ /local/arduino/hardware/arduino/avr/libraries/Wire/ 

include ../../../Makefile.master

