
# Board settings.
#BOARD = atmega328

LIB_DIRS = ../../ /usr/share/arduino-100/libraries/SPI/ /usr/share/arduino-100/libraries/Wire/ /usr/share/arduino-100/libraries/Wire/utility/

include ../../../Makefile.master

